name: Lindy Webhook Integration

on:
  push:
      branches: [main, master]

      jobs:
        notify-lindy:
            runs-on: ubuntu-latest
                steps:
                    - uses: actions/checkout@v4
                        - name: Send webhook to Lindy
                              run: |
                                      echo "Sending webhook to Lindy..."
                                              curl -X POST \
                                                        -H "Content-Type: application/json" \
                                                                  -H "Authorization: Bearer ${{ secrets.LINDY_WEBHOOK_SECRET }}" \
                                                                            -d '{"event":"${{ github.event_name }}","repository":"${{ github.repository }}","ref":"${{ github.ref }}","sha":"${{ github.sha }}","actor":"${{ github.actor }}"}' \
                                                                                      "https://webhook.lindy.ai/webhook/${{ secrets.LINDY_WEBHOOK_URL_ID }}" || echo "Webhook completed"
