name: Lindy Webhook Integration

on:
  push:
      branches: [main, master]
        pull_request:
            branches: [main, master]

            jobs:
              notify-lindy:
                  runsname: Lindy Webhook Integration

                  on:
                    push:
                        branches: [main, master]

                        jobs:
                          notify-lindy:
                              runs-on: ubuntu-latest
                                  steps:
                                      - uses: actions/checkout@v4
                                          - run: echo "Webhook test successful"
